# Project: feshorde sazi
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "feshorde\ sazi.o"
LINKOBJ  = "feshorde sazi.o"
LIBS     = -L"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/lib" -L"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/include" -I"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/include" -I"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/sajad/Downloads/Compressed/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = "feshorde sazi.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"feshorde\ sazi.o": feshorde\ sazi.cpp
	$(CPP) -c "feshorde sazi.cpp" -o "feshorde sazi.o" $(CXXFLAGS)
